FROM amazeeio/php:8.1-cli-drupal

COPY ./drupal/composer.* /app/
RUN composer install --no-dev
COPY ./drupal/ /app
RUN mkdir -p -v -m775 /app/web/sites/default/files

# Define where the Drupal Root is located
ENV WEBROOT=web
