#!/bin/bash

## Description: Install Drupal
## Usage: drupal-install
## Example: "ddev drupal-install"

composer install
drush -y site:install commerce_kickstart
drush -y pm:enable commerce_demo druxt
drush role:perm:add anonymous "access druxt resources"
drush mailer:import
drush cache:rebuild
